### ISSUE TITLE
Bard does not exist anymore (now is Gemini)

### ISSUE THREAD

**Issue by jlazoD** [sys-walker/delete-chats-caballo#1]
Will you update this wonderful extension so it can still work with gemini?
![Screenshot 2024-02-09 114628](https://github.com/sys-walker/delete-chats-caballo/assets/141733425/dd12c867-10e9-42ee-bb15-7f5976a89567)

**Comment by sys-walker** [comment]
Done! Regarding the design, it is already something that will be done in the future
